project:
  type: book

book:
  title: "hunterr_2024"
  author: "Hunter Vooys"
  date: "5/5/2024"
  search:
    location: sidebar
    type: overlay
    keyboard-shortcut: "/"
  repo-url: https://github.com/huntervooys/hunterr_2024
  repo-actions: [edit, issue]
  cover-image: assets/cover.png
  bread-crumbs: false
  sidebar:
    style: "docked"
    background: "light"
    type: "dark"
    border: true
    alignment: "center"
  chapters:
    - index.qmd
    - part: "R and Friends"
      chapters:
      - 01_lore.qmd
      - 02_r_and_friends.qmd
      - 03_r_101.qmd
      - 04_visualization.qmd
    - part: "Statistics"
      chapters:
        - 05_probability.qmd
        - 06_eugenics.qmd
    - 0R_references.qmd
  appendices:
    - 0A_resources.qmd

bibliography: references.bib

format:
  html:
    theme: zephyr
    toc: true
    toc-location: right
    toc-title: "on this page"
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true
    code-fold: show
    code-summary: "show code for this result"
    code-tools: true
    code-line-numbers: true
    code-copy: hover
    df-print: paged
    fig-align: center
    callout-appearance: simple

editor: visual

