project:
  type: book

book:
  title: "hunterr_2024"
  author: "Hunter Vooys"
  date: "5/5/2024"
  chapters:
    - index.qmd
    - part: "R and Friends"
      chapters:
      - intro.qmd
    - part: "Statistics"
      chapters:
      - summary.qmd
    - references.qmd
  appendices:
    - appendix.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

