# Preface {.unnumbered}

### Learning Objectives

-   discuss R as a language with a history, describe the purpose of R, and to use knowledge of the history and purpose of R to make sense of the structure of R expressions

    -   Read R expressions

    -   Write R expressions that are readable and align with the best practices of the open source R community

-   describe R's relationship to RStudio, RMarkdown, Shiny, Quarto, and Tidyverse; and describe the purpose of these various tools

    -   run R code in several different ways: via a terminal, a console, a script, and RMarkdown documents

-   use R to read, write, and pre-process[^index-1] rectangular data in a consistent, efficient, and minimally complex manner

    -   import data from a variety of sources including: comma-separated values (`.csv`) files, excel spreadshees (`.xlsx` files), google sheets spreadsheets

    -   'tidy' data into the following format: one observation per row, one variable per column, one value per cell

    -   generate synthetic data

    -   use available tools that enable you to store data in a very consistent format with very little effort

-   use R to process data

    -   describe R's data types and the use of each: strings, numerics (floating point "doubles", integers, and complex numbers), logicals, datetimes, and factors

    -   describe R's data structures and the use of each: including, vectors (1-dimensional arrays), matrices (2-dimensional arrays), arrays (more than 2-dimensional arrays), lists (key-value pairs), data frames, and tibbles

    -   use R to process string data by converting it to all lower case, adding a prefix or suffix, etc.

    -   use R to process numeric data by centering and scaling (normalizing) and performing other mathematical operations on data

-   use R and the grammar of graphics (represented by `ggplot2` and related packages) to visualize data and to share data visualizations with others

-   use simulation of simple events (like the rolling of dice or flipping of a coin) to gain visual intuition for the central limit theorem and the law of large numbers

-   use R to perform null-hypothesis significance tests, such as the one-sample, two-sample, and repeated measures t-test

    -   use the Monte Carlo framework to test the effect of violating the assumptions of statistical tests

-   use the Monte Carlo framework to do sample size calculations

-   use RMarkdown to conduct a linear or logistic regression, and to report and interpret the results of those tests

-   use R to perform a more complicated machine learning task, likely by constructing a decision tree and a random forest classification model

-   explain why dimension-reduction methods are used, and use R to perform one of these methods (likely a principal component analysis)

-   use R to pre-process, analyze and visualize text data

    -   apply the principles of natural language processing to pre-process text data (by tokenizing and stemming text and describing both of those processes and why they are used)

    -   use R to construct a vector space semantic model (likely a latent semantic analysis) and to report the results of such a model

-   access R documentation, and read it effectively enough to solve a problem

[^index-1]: pre-processing here refers to very basic, non-mathematical data processing tasks. Pre-processing involves developing a principled framework for storing data and then converting data from the wild into that format.
